// generated by "sampctl package generate"

#include "optud.inc"

#include <a_samp>

main() {
	// write tests for libraries here and run "sampctl package run"
}

public OnAntiCheatTurnUpsideDown(playerid, Float:angle) {
	printf("OnAntiCheatTurnUpsideDown: %d %f", playerid, angle);
}